/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./types"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `Upload` scalar type represents a file upload.
     */
    upload<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Upload";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `Upload` scalar type represents a file upload.
     */
    upload<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Upload";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AdminOrderByWithRelationInput: { // input type
    created_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    login_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    password?: NexusGenEnums['SortOrder'] | null; // SortOrder
    product?: NexusGenInputs['ProductOrderByRelationAggregateInput'] | null; // ProductOrderByRelationAggregateInput
    state?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  AdminWhereInput: { // input type
    AND?: NexusGenInputs['AdminWhereInput'][] | null; // [AdminWhereInput!]
    NOT?: NexusGenInputs['AdminWhereInput'][] | null; // [AdminWhereInput!]
    OR?: NexusGenInputs['AdminWhereInput'][] | null; // [AdminWhereInput!]
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    login_id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    password?: NexusGenInputs['StringFilter'] | null; // StringFilter
    product?: NexusGenInputs['ProductListRelationFilter'] | null; // ProductListRelationFilter
    state?: NexusGenInputs['EnumAdminStateFilter'] | null; // EnumAdminStateFilter
  }
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  CategoryOrderByWithRelationInput: { // input type
    a077_code?: NexusGenEnums['SortOrder'] | null; // SortOrder
    a112_code?: NexusGenEnums['SortOrder'] | null; // SortOrder
    b378_code?: NexusGenEnums['SortOrder'] | null; // SortOrder
    c1?: NexusGenEnums['SortOrder'] | null; // SortOrder
    c1_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    c2?: NexusGenEnums['SortOrder'] | null; // SortOrder
    c2_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    c3?: NexusGenEnums['SortOrder'] | null; // SortOrder
    c3_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    c4?: NexusGenEnums['SortOrder'] | null; // SortOrder
    c4_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    code?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    product?: NexusGenInputs['ProductOrderByRelationAggregateInput'] | null; // ProductOrderByRelationAggregateInput
    siil_code?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  CategoryWhereInput: { // input type
    AND?: NexusGenInputs['CategoryWhereInput'][] | null; // [CategoryWhereInput!]
    NOT?: NexusGenInputs['CategoryWhereInput'][] | null; // [CategoryWhereInput!]
    OR?: NexusGenInputs['CategoryWhereInput'][] | null; // [CategoryWhereInput!]
    a077_code?: NexusGenInputs['StringFilter'] | null; // StringFilter
    a112_code?: NexusGenInputs['IntFilter'] | null; // IntFilter
    b378_code?: NexusGenInputs['IntFilter'] | null; // IntFilter
    c1?: NexusGenInputs['StringFilter'] | null; // StringFilter
    c1_name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    c2?: NexusGenInputs['StringFilter'] | null; // StringFilter
    c2_name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    c3?: NexusGenInputs['StringFilter'] | null; // StringFilter
    c3_name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    c4?: NexusGenInputs['StringFilter'] | null; // StringFilter
    c4_name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    code?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    product?: NexusGenInputs['ProductListRelationFilter'] | null; // ProductListRelationFilter
    siil_code?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  EnumAdminStateFilter: { // input type
    equals?: NexusGenEnums['AdminState'] | null; // AdminState
    in?: NexusGenEnums['AdminState'][] | null; // [AdminState!]
    not?: NexusGenInputs['NestedEnumAdminStateFilter'] | null; // NestedEnumAdminStateFilter
    notIn?: NexusGenEnums['AdminState'][] | null; // [AdminState!]
  }
  EnumProductStateFilter: { // input type
    equals?: NexusGenEnums['ProductState'] | null; // ProductState
    in?: NexusGenEnums['ProductState'][] | null; // [ProductState!]
    not?: NexusGenInputs['NestedEnumProductStateFilter'] | null; // NestedEnumProductStateFilter
    notIn?: NexusGenEnums['ProductState'][] | null; // [ProductState!]
  }
  EnumUserStateFilter: { // input type
    equals?: NexusGenEnums['UserState'] | null; // UserState
    in?: NexusGenEnums['UserState'][] | null; // [UserState!]
    not?: NexusGenInputs['NestedEnumUserStateFilter'] | null; // NestedEnumUserStateFilter
    notIn?: NexusGenEnums['UserState'][] | null; // [UserState!]
  }
  FloatFilter: { // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: number[] | null; // [Float!]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    notIn?: number[] | null; // [Float!]
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedEnumAdminStateFilter: { // input type
    equals?: NexusGenEnums['AdminState'] | null; // AdminState
    in?: NexusGenEnums['AdminState'][] | null; // [AdminState!]
    not?: NexusGenInputs['NestedEnumAdminStateFilter'] | null; // NestedEnumAdminStateFilter
    notIn?: NexusGenEnums['AdminState'][] | null; // [AdminState!]
  }
  NestedEnumProductStateFilter: { // input type
    equals?: NexusGenEnums['ProductState'] | null; // ProductState
    in?: NexusGenEnums['ProductState'][] | null; // [ProductState!]
    not?: NexusGenInputs['NestedEnumProductStateFilter'] | null; // NestedEnumProductStateFilter
    notIn?: NexusGenEnums['ProductState'][] | null; // [ProductState!]
  }
  NestedEnumUserStateFilter: { // input type
    equals?: NexusGenEnums['UserState'] | null; // UserState
    in?: NexusGenEnums['UserState'][] | null; // [UserState!]
    not?: NexusGenInputs['NestedEnumUserStateFilter'] | null; // NestedEnumUserStateFilter
    notIn?: NexusGenEnums['UserState'][] | null; // [UserState!]
  }
  NestedFloatFilter: { // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: number[] | null; // [Float!]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    notIn?: number[] | null; // [Float!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  ProductListRelationFilter: { // input type
    every?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    none?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    some?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
  }
  ProductOptionListRelationFilter: { // input type
    every?: NexusGenInputs['ProductOptionWhereInput'] | null; // ProductOptionWhereInput
    none?: NexusGenInputs['ProductOptionWhereInput'] | null; // ProductOptionWhereInput
    some?: NexusGenInputs['ProductOptionWhereInput'] | null; // ProductOptionWhereInput
  }
  ProductOptionNameListRelationFilter: { // input type
    every?: NexusGenInputs['ProductOptionNameWhereInput'] | null; // ProductOptionNameWhereInput
    none?: NexusGenInputs['ProductOptionNameWhereInput'] | null; // ProductOptionNameWhereInput
    some?: NexusGenInputs['ProductOptionNameWhereInput'] | null; // ProductOptionNameWhereInput
  }
  ProductOptionNameOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
    count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ProductOptionNameWhereInput: { // input type
    AND?: NexusGenInputs['ProductOptionNameWhereInput'][] | null; // [ProductOptionNameWhereInput!]
    NOT?: NexusGenInputs['ProductOptionNameWhereInput'][] | null; // [ProductOptionNameWhereInput!]
    OR?: NexusGenInputs['ProductOptionNameWhereInput'][] | null; // [ProductOptionNameWhereInput!]
    has_image?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    is_name_translated?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    order?: NexusGenInputs['IntFilter'] | null; // IntFilter
    product?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    product_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    product_option_value?: NexusGenInputs['ProductOptionValueListRelationFilter'] | null; // ProductOptionValueListRelationFilter
    taobao_pid?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  ProductOptionOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
    count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ProductOptionValueListRelationFilter: { // input type
    every?: NexusGenInputs['ProductOptionValueWhereInput'] | null; // ProductOptionValueWhereInput
    none?: NexusGenInputs['ProductOptionValueWhereInput'] | null; // ProductOptionValueWhereInput
    some?: NexusGenInputs['ProductOptionValueWhereInput'] | null; // ProductOptionValueWhereInput
  }
  ProductOptionValueWhereInput: { // input type
    AND?: NexusGenInputs['ProductOptionValueWhereInput'][] | null; // [ProductOptionValueWhereInput!]
    NOT?: NexusGenInputs['ProductOptionValueWhereInput'][] | null; // [ProductOptionValueWhereInput!]
    OR?: NexusGenInputs['ProductOptionValueWhereInput'][] | null; // [ProductOptionValueWhereInput!]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    image?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    is_active?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    is_name_translated?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    number?: NexusGenInputs['IntFilter'] | null; // IntFilter
    option_name_order?: NexusGenInputs['IntFilter'] | null; // IntFilter
    option_value1?: NexusGenInputs['ProductOptionListRelationFilter'] | null; // ProductOptionListRelationFilter
    option_value2?: NexusGenInputs['ProductOptionListRelationFilter'] | null; // ProductOptionListRelationFilter
    option_value3?: NexusGenInputs['ProductOptionListRelationFilter'] | null; // ProductOptionListRelationFilter
    product_option_name?: NexusGenInputs['ProductOptionNameWhereInput'] | null; // ProductOptionNameWhereInput
    product_option_name_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    taobao_vid?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  ProductOptionWhereInput: { // input type
    AND?: NexusGenInputs['ProductOptionWhereInput'][] | null; // [ProductOptionWhereInput!]
    NOT?: NexusGenInputs['ProductOptionWhereInput'][] | null; // [ProductOptionWhereInput!]
    OR?: NexusGenInputs['ProductOptionWhereInput'][] | null; // [ProductOptionWhereInput!]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    is_active?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    option_string?: NexusGenInputs['StringFilter'] | null; // StringFilter
    option_value1_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    option_value2_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    option_value3_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    price?: NexusGenInputs['IntFilter'] | null; // IntFilter
    price_cny?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    product?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    product_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    product_option1?: NexusGenInputs['ProductOptionValueWhereInput'] | null; // ProductOptionValueWhereInput
    product_option2?: NexusGenInputs['ProductOptionValueWhereInput'] | null; // ProductOptionValueWhereInput
    product_option3?: NexusGenInputs['ProductOptionValueWhereInput'] | null; // ProductOptionValueWhereInput
    stock?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    taobao_sku_id?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  ProductOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
    count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ProductOrderByWithRelationInput: { // input type
    admin?: NexusGenInputs['AdminOrderByWithRelationInput'] | null; // AdminOrderByWithRelationInput
    admin_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category?: NexusGenInputs['CategoryOrderByWithRelationInput'] | null; // CategoryOrderByWithRelationInput
    category_a001?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a001_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a006?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a006_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a027?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a027_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a077?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a077_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a112?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a112_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a113?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a113_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a524?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a524_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a525?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_a525_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_b378?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_b378_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_b719?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_b719_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_b956?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_b956_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_code?: NexusGenEnums['SortOrder'] | null; // SortOrder
    category_esm?: NexusGenEnums['SortOrder'] | null; // SortOrder
    cny_rate?: NexusGenEnums['SortOrder'] | null; // SortOrder
    created_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    description?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    image_thumbnail_data?: NexusGenEnums['SortOrder'] | null; // SortOrder
    is_image_translated?: NexusGenEnums['SortOrder'] | null; // SortOrder
    is_name_translated?: NexusGenEnums['SortOrder'] | null; // SortOrder
    local_shipping_code?: NexusGenEnums['SortOrder'] | null; // SortOrder
    local_shipping_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    margin_rate?: NexusGenEnums['SortOrder'] | null; // SortOrder
    margin_unit_type?: NexusGenEnums['SortOrder'] | null; // SortOrder
    modified_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    price?: NexusGenEnums['SortOrder'] | null; // SortOrder
    product_code?: NexusGenEnums['SortOrder'] | null; // SortOrder
    product_option?: NexusGenInputs['ProductOptionOrderByRelationAggregateInput'] | null; // ProductOptionOrderByRelationAggregateInput
    product_option_name?: NexusGenInputs['ProductOptionNameOrderByRelationAggregateInput'] | null; // ProductOptionNameOrderByRelationAggregateInput
    search_tags?: NexusGenEnums['SortOrder'] | null; // SortOrder
    shipping_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    siil_code?: NexusGenEnums['SortOrder'] | null; // SortOrder
    siil_data?: NexusGenEnums['SortOrder'] | null; // SortOrder
    state?: NexusGenEnums['SortOrder'] | null; // SortOrder
    stock_updated_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    taobao_product?: NexusGenInputs['TaobaoProductOrderByWithRelationInput'] | null; // TaobaoProductOrderByWithRelationInput
    taobao_product_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    user?: NexusGenInputs['UserOrderByWithRelationInput'] | null; // UserOrderByWithRelationInput
    user_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ProductUQ_user_id_taobao_product_idCompoundUniqueInput: { // input type
    taobao_product_id: number; // Int!
    user_id: number; // Int!
  }
  ProductWhereInput: { // input type
    AND?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    NOT?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    OR?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    admin?: NexusGenInputs['AdminWhereInput'] | null; // AdminWhereInput
    admin_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    category?: NexusGenInputs['CategoryWhereInput'] | null; // CategoryWhereInput
    category_a001?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a001_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a006?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a006_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a027?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a027_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a077?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a077_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a112?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a112_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a113?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a113_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a524?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a524_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a525?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_a525_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_b378?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_b378_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_b719?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_b719_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_b956?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_b956_name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_code?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    category_esm?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    cny_rate?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    image_thumbnail_data?: NexusGenInputs['StringFilter'] | null; // StringFilter
    is_image_translated?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    is_name_translated?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    local_shipping_code?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    local_shipping_fee?: NexusGenInputs['IntFilter'] | null; // IntFilter
    margin_rate?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    margin_unit_type?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    modified_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    price?: NexusGenInputs['IntFilter'] | null; // IntFilter
    product_code?: NexusGenInputs['StringFilter'] | null; // StringFilter
    product_option?: NexusGenInputs['ProductOptionListRelationFilter'] | null; // ProductOptionListRelationFilter
    product_option_name?: NexusGenInputs['ProductOptionNameListRelationFilter'] | null; // ProductOptionNameListRelationFilter
    search_tags?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    shipping_fee?: NexusGenInputs['IntFilter'] | null; // IntFilter
    siil_code?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    siil_data?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    state?: NexusGenInputs['EnumProductStateFilter'] | null; // EnumProductStateFilter
    stock_updated_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    taobao_product?: NexusGenInputs['TaobaoProductWhereInput'] | null; // TaobaoProductWhereInput
    taobao_product_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    user_id?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
  }
  ProductWhereUniqueInput: { // input type
    UQ_user_id_taobao_product_id?: NexusGenInputs['ProductUQ_user_id_taobao_product_idCompoundUniqueInput'] | null; // ProductUQ_user_id_taobao_product_idCompoundUniqueInput
    id?: number | null; // Int
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  TaobaoProductOrderByWithRelationInput: { // input type
    brand?: NexusGenEnums['SortOrder'] | null; // SortOrder
    created_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    image_thumbnail?: NexusGenEnums['SortOrder'] | null; // SortOrder
    modified_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    original_data?: NexusGenEnums['SortOrder'] | null; // SortOrder
    price?: NexusGenEnums['SortOrder'] | null; // SortOrder
    product?: NexusGenInputs['ProductOrderByRelationAggregateInput'] | null; // ProductOrderByRelationAggregateInput
    taobao_brand_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    taobao_category_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    taobao_num_iid?: NexusGenEnums['SortOrder'] | null; // SortOrder
    translate_data?: NexusGenEnums['SortOrder'] | null; // SortOrder
    video_url?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  TaobaoProductWhereInput: { // input type
    AND?: NexusGenInputs['TaobaoProductWhereInput'][] | null; // [TaobaoProductWhereInput!]
    NOT?: NexusGenInputs['TaobaoProductWhereInput'][] | null; // [TaobaoProductWhereInput!]
    OR?: NexusGenInputs['TaobaoProductWhereInput'][] | null; // [TaobaoProductWhereInput!]
    brand?: NexusGenInputs['StringFilter'] | null; // StringFilter
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    image_thumbnail?: NexusGenInputs['StringFilter'] | null; // StringFilter
    modified_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    original_data?: NexusGenInputs['StringFilter'] | null; // StringFilter
    price?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    product?: NexusGenInputs['ProductListRelationFilter'] | null; // ProductListRelationFilter
    taobao_brand_id?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    taobao_category_id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    taobao_num_iid?: NexusGenInputs['StringFilter'] | null; // StringFilter
    translate_data?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    video_url?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
  }
  UserInfoOrderByWithRelationInput: { // input type
    additional_shipping_fee_jeju?: NexusGenEnums['SortOrder'] | null; // SortOrder
    as_information?: NexusGenEnums['SortOrder'] | null; // SortOrder
    as_tel?: NexusGenEnums['SortOrder'] | null; // SortOrder
    auction_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    cny_rate?: NexusGenEnums['SortOrder'] | null; // SortOrder
    collect_stock?: NexusGenEnums['SortOrder'] | null; // SortOrder
    collect_timeout?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_access_key?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_default_inbound?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_default_outbound?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_image_opt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_login_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_maximum_buy_for_person?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_outbound_shipping_time_day?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_secret_key?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_union_delivery_type?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coupang_vendor_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    default_shipping_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    description_show_title?: NexusGenEnums['SortOrder'] | null; // SortOrder
    discount_amount?: NexusGenEnums['SortOrder'] | null; // SortOrder
    discount_unit_type?: NexusGenEnums['SortOrder'] | null; // SortOrder
    esmplus_auction_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    esmplus_gmarket_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    esmplus_master_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    exchange_shipping_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    extra_shipping_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    fix_image_bottom?: NexusGenEnums['SortOrder'] | null; // SortOrder
    fix_image_top?: NexusGenEnums['SortOrder'] | null; // SortOrder
    gmarket_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    interpark_cert_key?: NexusGenEnums['SortOrder'] | null; // SortOrder
    interpark_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    interpark_secret_key?: NexusGenEnums['SortOrder'] | null; // SortOrder
    lotteon_api_key?: NexusGenEnums['SortOrder'] | null; // SortOrder
    lotteon_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    lotteon_normal_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    lotteon_vendor_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    margin_rate?: NexusGenEnums['SortOrder'] | null; // SortOrder
    margin_unit_type?: NexusGenEnums['SortOrder'] | null; // SortOrder
    max_product_limit?: NexusGenEnums['SortOrder'] | null; // SortOrder
    naver_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    naver_origin?: NexusGenEnums['SortOrder'] | null; // SortOrder
    naver_origin_code?: NexusGenEnums['SortOrder'] | null; // SortOrder
    naver_store_only?: NexusGenEnums['SortOrder'] | null; // SortOrder
    naver_store_url?: NexusGenEnums['SortOrder'] | null; // SortOrder
    option_align_top?: NexusGenEnums['SortOrder'] | null; // SortOrder
    option_index_type?: NexusGenEnums['SortOrder'] | null; // SortOrder
    option_twoways?: NexusGenEnums['SortOrder'] | null; // SortOrder
    phone?: NexusGenEnums['SortOrder'] | null; // SortOrder
    product_collect_count?: NexusGenEnums['SortOrder'] | null; // SortOrder
    refund_shipping_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    street_api_key?: NexusGenEnums['SortOrder'] | null; // SortOrder
    street_default_inbound?: NexusGenEnums['SortOrder'] | null; // SortOrder
    street_default_outbound?: NexusGenEnums['SortOrder'] | null; // SortOrder
    street_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    street_normal_api_key?: NexusGenEnums['SortOrder'] | null; // SortOrder
    street_normal_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    street_normal_inbound?: NexusGenEnums['SortOrder'] | null; // SortOrder
    street_normal_outbound?: NexusGenEnums['SortOrder'] | null; // SortOrder
    street_seller_type?: NexusGenEnums['SortOrder'] | null; // SortOrder
    tmon_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    tmon_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    user?: NexusGenInputs['UserOrderByWithRelationInput'] | null; // UserOrderByWithRelationInput
    user_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    wemakeprice_fee?: NexusGenEnums['SortOrder'] | null; // SortOrder
    wemakeprice_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserInfoWhereInput: { // input type
    AND?: NexusGenInputs['UserInfoWhereInput'][] | null; // [UserInfoWhereInput!]
    NOT?: NexusGenInputs['UserInfoWhereInput'][] | null; // [UserInfoWhereInput!]
    OR?: NexusGenInputs['UserInfoWhereInput'][] | null; // [UserInfoWhereInput!]
    additional_shipping_fee_jeju?: NexusGenInputs['IntFilter'] | null; // IntFilter
    as_information?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    as_tel?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    auction_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    cny_rate?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    collect_stock?: NexusGenInputs['IntFilter'] | null; // IntFilter
    collect_timeout?: NexusGenInputs['IntFilter'] | null; // IntFilter
    coupang_access_key?: NexusGenInputs['StringFilter'] | null; // StringFilter
    coupang_default_inbound?: NexusGenInputs['StringFilter'] | null; // StringFilter
    coupang_default_outbound?: NexusGenInputs['StringFilter'] | null; // StringFilter
    coupang_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    coupang_image_opt?: NexusGenInputs['StringFilter'] | null; // StringFilter
    coupang_login_id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    coupang_maximum_buy_for_person?: NexusGenInputs['IntFilter'] | null; // IntFilter
    coupang_outbound_shipping_time_day?: NexusGenInputs['IntFilter'] | null; // IntFilter
    coupang_secret_key?: NexusGenInputs['StringFilter'] | null; // StringFilter
    coupang_union_delivery_type?: NexusGenInputs['StringFilter'] | null; // StringFilter
    coupang_vendor_id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    default_shipping_fee?: NexusGenInputs['IntFilter'] | null; // IntFilter
    description_show_title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    discount_amount?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    discount_unit_type?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    esmplus_auction_id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    esmplus_gmarket_id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    esmplus_master_id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    exchange_shipping_fee?: NexusGenInputs['IntFilter'] | null; // IntFilter
    extra_shipping_fee?: NexusGenInputs['IntFilter'] | null; // IntFilter
    fix_image_bottom?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    fix_image_top?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    gmarket_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    interpark_cert_key?: NexusGenInputs['StringFilter'] | null; // StringFilter
    interpark_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    interpark_secret_key?: NexusGenInputs['StringFilter'] | null; // StringFilter
    lotteon_api_key?: NexusGenInputs['StringFilter'] | null; // StringFilter
    lotteon_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    lotteon_normal_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    lotteon_vendor_id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    margin_rate?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    margin_unit_type?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    max_product_limit?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    naver_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    naver_origin?: NexusGenInputs['StringFilter'] | null; // StringFilter
    naver_origin_code?: NexusGenInputs['StringFilter'] | null; // StringFilter
    naver_store_only?: NexusGenInputs['StringFilter'] | null; // StringFilter
    naver_store_url?: NexusGenInputs['StringFilter'] | null; // StringFilter
    option_align_top?: NexusGenInputs['StringFilter'] | null; // StringFilter
    option_index_type?: NexusGenInputs['IntFilter'] | null; // IntFilter
    option_twoways?: NexusGenInputs['StringFilter'] | null; // StringFilter
    phone?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    product_collect_count?: NexusGenInputs['IntFilter'] | null; // IntFilter
    refund_shipping_fee?: NexusGenInputs['IntFilter'] | null; // IntFilter
    street_api_key?: NexusGenInputs['StringFilter'] | null; // StringFilter
    street_default_inbound?: NexusGenInputs['StringFilter'] | null; // StringFilter
    street_default_outbound?: NexusGenInputs['StringFilter'] | null; // StringFilter
    street_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    street_normal_api_key?: NexusGenInputs['StringFilter'] | null; // StringFilter
    street_normal_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    street_normal_inbound?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    street_normal_outbound?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    street_seller_type?: NexusGenInputs['IntFilter'] | null; // IntFilter
    tmon_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    tmon_id?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    user_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    wemakeprice_fee?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    wemakeprice_id?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  UserLogListRelationFilter: { // input type
    every?: NexusGenInputs['UserLogWhereInput'] | null; // UserLogWhereInput
    none?: NexusGenInputs['UserLogWhereInput'] | null; // UserLogWhereInput
    some?: NexusGenInputs['UserLogWhereInput'] | null; // UserLogWhereInput
  }
  UserLogOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
    count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserLogOrderByWithRelationInput: { // input type
    created_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    is_read?: NexusGenEnums['SortOrder'] | null; // SortOrder
    payload_data?: NexusGenEnums['SortOrder'] | null; // SortOrder
    title?: NexusGenEnums['SortOrder'] | null; // SortOrder
    user?: NexusGenInputs['UserOrderByWithRelationInput'] | null; // UserOrderByWithRelationInput
    user_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserLogWhereInput: { // input type
    AND?: NexusGenInputs['UserLogWhereInput'][] | null; // [UserLogWhereInput!]
    NOT?: NexusGenInputs['UserLogWhereInput'][] | null; // [UserLogWhereInput!]
    OR?: NexusGenInputs['UserLogWhereInput'][] | null; // [UserLogWhereInput!]
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    is_read?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    payload_data?: NexusGenInputs['StringFilter'] | null; // StringFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    user_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  UserLogWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  UserOrderByWithRelationInput: { // input type
    created_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    kakao_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    naver_id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    password?: NexusGenEnums['SortOrder'] | null; // SortOrder
    product?: NexusGenInputs['ProductOrderByRelationAggregateInput'] | null; // ProductOrderByRelationAggregateInput
    state?: NexusGenEnums['SortOrder'] | null; // SortOrder
    user_info?: NexusGenInputs['UserInfoOrderByWithRelationInput'] | null; // UserInfoOrderByWithRelationInput
    user_log?: NexusGenInputs['UserLogOrderByRelationAggregateInput'] | null; // UserLogOrderByRelationAggregateInput
  }
  UserWhereInput: { // input type
    AND?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    NOT?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    OR?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    email?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    kakao_id?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    naver_id?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    password?: NexusGenInputs['StringFilter'] | null; // StringFilter
    product?: NexusGenInputs['ProductListRelationFilter'] | null; // ProductListRelationFilter
    state?: NexusGenInputs['EnumUserStateFilter'] | null; // EnumUserStateFilter
    user_info?: NexusGenInputs['UserInfoWhereInput'] | null; // UserInfoWhereInput
    user_log?: NexusGenInputs['UserLogListRelationFilter'] | null; // UserLogListRelationFilter
  }
}

export interface NexusGenEnums {
  AdminState: "ACTIVE" | "DELETED"
  ProductState: "COLLECTED" | "ON_SALE" | "SELL_DONE" | "UPLOAD_FAILED" | "UPLOAD_WAITING"
  SortOrder: "asc" | "desc"
  TaobaoItemOrderBy: "_credit" | "_sale"
  UserLoginType: "ADMIN" | "EMAIL" | "KAKAO" | "NAVER"
  UserSocialType: "EMAIL" | "KAKAO" | "NAVER"
  UserState: "ACTIVE" | "DELETED"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: Date
  Upload: FileUpload
}

export interface NexusGenObjects {
  AccountInfo: { // root type
    accountHolder: string; // String!
    accountNumber: string; // String!
    bankName: string; // String!
  }
  Admin: { // root type
    created_at: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    login_id: string; // String!
    state: NexusGenEnums['AdminState']; // AdminState!
  }
  Mutation: {};
  PhoneVerification: { // root type
    created_at: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    tel: string; // String!
    verification_number: string; // String!
  }
  Product: { // root type
    admin_id?: number | null; // Int
    category_code?: string | null; // String
    created_at: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    id: number; // Int!
    image_thumbnail_data: string; // String!
    is_image_translated: boolean; // Boolean!
    is_name_translated: boolean; // Boolean!
    local_shipping_fee: number; // Int!
    modified_at: NexusGenScalars['DateTime']; // DateTime!
    name: string; // String!
    price: number; // Int!
    product_code: string; // String!
    siil_code?: string | null; // String
    siil_data?: string | null; // String
    state: NexusGenEnums['ProductState']; // ProductState!
    stock_updated_at: NexusGenScalars['DateTime']; // DateTime!
    taobao_product_id: number; // Int!
    user_id?: number | null; // Int
  }
  Query: {};
  SignInType: { // root type
    accessToken: string; // String!
    refreshToken: string; // String!
  }
  User: { // root type
    created_at: NexusGenScalars['DateTime']; // DateTime!
    email: string; // String!
    id: number; // Int!
    kakao_id?: string | null; // String
    naver_id?: string | null; // String
    state: NexusGenEnums['UserState']; // UserState!
  }
  UserInfo: { // root type
    as_information?: string | null; // String
    as_tel?: string | null; // String
    cny_rate: number; // Float!
    default_shipping_fee: number; // Int!
    exchange_shipping_fee: number; // Int!
    fix_image_bottom?: string | null; // String
    fix_image_top?: string | null; // String
    margin_rate: number; // Float!
    max_product_limit?: number | null; // Int
    phone?: string | null; // String
    product_collect_count: number; // Int!
    refund_shipping_fee: number; // Int!
    user_id: number; // Int!
  }
  UserLog: { // root type
    created_at: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    is_read: boolean; // Boolean!
    payload_data: string; // String!
    title: string; // String!
    user_id: number; // Int!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AccountInfo: { // field return type
    accountHolder: string; // String!
    accountNumber: string; // String!
    bankName: string; // String!
  }
  Admin: { // field return type
    created_at: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    login_id: string; // String!
    state: NexusGenEnums['AdminState']; // AdminState!
  }
  Mutation: { // field return type
    changeMyPasswordByAdmin: boolean; // Boolean!
    renewToken: NexusGenRootTypes['SignInType'] | null; // SignInType
    requestPhoneVerificationByEveryone: boolean; // Boolean!
    signUpAdminByAdmin: boolean; // Boolean!
    verifyPhoneByEveryone: number; // Int!
  }
  PhoneVerification: { // field return type
    created_at: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    tel: string; // String!
    verification_number: string; // String!
  }
  Product: { // field return type
    admin_id: number | null; // Int
    category_code: string | null; // String
    created_at: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    id: number; // Int!
    imageThumbnail: string[]; // [String!]!
    image_thumbnail_data: string; // String!
    is_image_translated: boolean; // Boolean!
    is_name_translated: boolean; // Boolean!
    local_shipping_fee: number; // Int!
    modified_at: NexusGenScalars['DateTime']; // DateTime!
    name: string; // String!
    price: number; // Int!
    product_code: string; // String!
    siil_code: string | null; // String
    siil_data: string | null; // String
    state: NexusGenEnums['ProductState']; // ProductState!
    stock_updated_at: NexusGenScalars['DateTime']; // DateTime!
    taobao_product_id: number; // Int!
    user: NexusGenRootTypes['User'] | null; // User
    user_id: number | null; // Int
  }
  Query: { // field return type
    ok: boolean; // Boolean!
  }
  SignInType: { // field return type
    accessToken: string; // String!
    refreshToken: string; // String!
  }
  User: { // field return type
    created_at: NexusGenScalars['DateTime']; // DateTime!
    email: string; // String!
    id: number; // Int!
    kakao_id: string | null; // String
    naver_id: string | null; // String
    password: string | null; // String
    product: NexusGenRootTypes['Product'][]; // [Product!]!
    state: NexusGenEnums['UserState']; // UserState!
    user_info: NexusGenRootTypes['UserInfo'] | null; // UserInfo
    user_log: NexusGenRootTypes['UserLog'][]; // [UserLog!]!
  }
  UserInfo: { // field return type
    as_information: string | null; // String
    as_tel: string | null; // String
    cny_rate: number; // Float!
    default_shipping_fee: number; // Int!
    exchange_shipping_fee: number; // Int!
    fix_image_bottom: string | null; // String
    fix_image_top: string | null; // String
    margin_rate: number; // Float!
    max_product_limit: number | null; // Int
    phone: string | null; // String
    product_collect_count: number; // Int!
    refund_shipping_fee: number; // Int!
    user: NexusGenRootTypes['User']; // User!
    user_id: number; // Int!
  }
  UserLog: { // field return type
    created_at: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    is_read: boolean; // Boolean!
    payload_data: string; // String!
    title: string; // String!
    user: NexusGenRootTypes['User']; // User!
    user_id: number; // Int!
  }
}

export interface NexusGenFieldTypeNames {
  AccountInfo: { // field return type name
    accountHolder: 'String'
    accountNumber: 'String'
    bankName: 'String'
  }
  Admin: { // field return type name
    created_at: 'DateTime'
    id: 'Int'
    login_id: 'String'
    state: 'AdminState'
  }
  Mutation: { // field return type name
    changeMyPasswordByAdmin: 'Boolean'
    renewToken: 'SignInType'
    requestPhoneVerificationByEveryone: 'Boolean'
    signUpAdminByAdmin: 'Boolean'
    verifyPhoneByEveryone: 'Int'
  }
  PhoneVerification: { // field return type name
    created_at: 'DateTime'
    id: 'Int'
    tel: 'String'
    verification_number: 'String'
  }
  Product: { // field return type name
    admin_id: 'Int'
    category_code: 'String'
    created_at: 'DateTime'
    description: 'String'
    id: 'Int'
    imageThumbnail: 'String'
    image_thumbnail_data: 'String'
    is_image_translated: 'Boolean'
    is_name_translated: 'Boolean'
    local_shipping_fee: 'Int'
    modified_at: 'DateTime'
    name: 'String'
    price: 'Int'
    product_code: 'String'
    siil_code: 'String'
    siil_data: 'String'
    state: 'ProductState'
    stock_updated_at: 'DateTime'
    taobao_product_id: 'Int'
    user: 'User'
    user_id: 'Int'
  }
  Query: { // field return type name
    ok: 'Boolean'
  }
  SignInType: { // field return type name
    accessToken: 'String'
    refreshToken: 'String'
  }
  User: { // field return type name
    created_at: 'DateTime'
    email: 'String'
    id: 'Int'
    kakao_id: 'String'
    naver_id: 'String'
    password: 'String'
    product: 'Product'
    state: 'UserState'
    user_info: 'UserInfo'
    user_log: 'UserLog'
  }
  UserInfo: { // field return type name
    as_information: 'String'
    as_tel: 'String'
    cny_rate: 'Float'
    default_shipping_fee: 'Int'
    exchange_shipping_fee: 'Int'
    fix_image_bottom: 'String'
    fix_image_top: 'String'
    margin_rate: 'Float'
    max_product_limit: 'Int'
    phone: 'String'
    product_collect_count: 'Int'
    refund_shipping_fee: 'Int'
    user: 'User'
    user_id: 'Int'
  }
  UserLog: { // field return type name
    created_at: 'DateTime'
    id: 'Int'
    is_read: 'Boolean'
    payload_data: 'String'
    title: 'String'
    user: 'User'
    user_id: 'Int'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    changeMyPasswordByAdmin: { // args
      currentPassword: string; // String!
      newPassword: string; // String!
    }
    renewToken: { // args
      accessToken: string; // String!
      refreshToken: string; // String!
    }
    requestPhoneVerificationByEveryone: { // args
      phoneNumber: string; // String!
    }
    signUpAdminByAdmin: { // args
      id: string; // String!
      password: string; // String!
    }
    verifyPhoneByEveryone: { // args
      phoneNumber: string; // String!
      verificationNumber: string; // String!
    }
  }
  User: {
    product: { // args
      cursor?: NexusGenInputs['ProductWhereUniqueInput'] | null; // ProductWhereUniqueInput
      orderBy?: NexusGenInputs['ProductOrderByWithRelationInput'][] | null; // [ProductOrderByWithRelationInput!]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    }
    user_log: { // args
      cursor?: NexusGenInputs['UserLogWhereUniqueInput'] | null; // UserLogWhereUniqueInput
      orderBy?: NexusGenInputs['UserLogOrderByWithRelationInput'][] | null; // [UserLogOrderByWithRelationInput!]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['UserLogWhereInput'] | null; // UserLogWhereInput
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}